server:
  port: 9001

feishu:
  appId:
  appSecret:
  encryptKey:
  verificationToken:

proxy:
  url: https://qqil.cn

logging:
  level:
    root: info
    com.rawchen: debug
    com.lark.oapi.event.EventDispatcher: off
    org.apache.coyote.http11.Http11Processor: warn




