server:
  port: 9001

feishu:
  appId: cli_a44axxxxxxxxxxx
  appSecret: 9GLUNqVTusxAxxxxxxxxxxxxxxxxxxxxx
  encryptKey:
  verificationToken:

proxy:
  url: https://api.baizhi.ai

logging:
  level:
    root: info
    com.rawchen: debug
    com.lark.oapi.event.EventDispatcher: off
    org.apache.coyote.http11.Http11Processor: warn




